[package]
name = "loco-keycloak-auth"
version = "0.1.0"
edition = "2024"
authors = ["Gabriel Kaszewski"]

[dependencies]
axum-keycloak-auth = { version = "0.8.2" }
axum = "0.8.3"
loco-rs = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.2"
